### ISSUE TITLE
Any plan change the footprint to 0805?

### ISSUE THREAD

**Issue by jcyfkimi** [mathisschmieder/MMDVM_HS_Hat#10]
Dear Sir
         Currently 0402 footprint is too small for hand soldering and I want to know any plan of change it to 0805?

**Comment by mathisschmieder** [comment]
Sorry, we don't have any plans to change the footprints to 0805 for several reasons. There would not be enough space on the board to use 0805 components. Besides, the ADF7021 is much harder to solder than 0402 components. There is a 0603 branch, but the ADF7021 still requires quite a bit soldering expertise.
