### ISSUE TITLE
The new revision's SMA antenna doesn't line up with available cases

### ISSUE THREAD

**Issue by jberry** [mathisschmieder/MMDVM_HS_Hat#11]
Would it be possible to generate a Kicad with the SMA in the original location (where the Ceramic antenna is now), so that we have the option of printing a rev 1.6 that is compatible with other hotspot cases?

**Comment by phl0** [comment]
We had to relocate the SMA socket due to more added components and thus the space between the two screw holes had to be used optimally. Placing the SMA socket there wasted too much space.

**Comment by phl0** [comment]
Btw: It is all open source. You are free to take the sources an re-route the SMA socket to where you want it to be. Or you use one of the cases that fit the current board layout. For example: https://www.thingiverse.com/thing:2801025

**Comment by jberry** [comment]
Ah, makes sense on the space usage, but glad to hear it should be feasible. I didn't see many components that appear to be in the way besides antenna + C28 and maybe C31.  I'll fireup KiCad and see what I can work up, always been an Eagle user =)

**Comment by phl0** [comment]
I guess it should be feasible. Especially if you then just leave out the SMD onboard antenna and only move the SMA connector.

**Comment by jberry** [comment]
Yeah, that's the plan, only do the SMA. Seems only that 1 thingiverse case has adopted the new antenna location (at least looking for mmdvm or zumspot searches), and 1 looks to be for ceramic only (even though it could be drilled out); a lot of the others, including nice metal cases such as https://i.ebayimg.com/images/g/2qcAAOSwDVtacnJC/s-l500.jpg , require the old SMA location.
