### ISSUE TITLE
BOM - More Specific Values

### ISSUE THREAD

**Issue by szechyjs** [mathisschmieder/MMDVM_HS_Hat#12]
I noticed that the BOM csv/xls list values (resistance, capacitance, etc) for passive components however they do not list tolerances and power ratings. Obviously the listed part numbers have these values associated with them, but it would be nice to know what parameters are required for each component. 

For example I have a bunch of 1k 1% resistors in my stock, however the part listed for R19 has a 0.5% tolerance. Having a more detailed BOM would help identify if these types of substitutions can be made.

**Comment by dd5xl** [comment]
Treat the supplied BoM as an example.
For the MMDVM-Hat it actually doesn't matter to distinguish between 1% and 0,5% tolerated components, this is a ham radio project, not a life-time-calibrated measuring device.
