### ISSUE TITLE
Couldn't get revision 1 PCB working

### ISSUE THREAD

**Issue by yngwiechou** [mathisschmieder/MMDVM_HS_Hat#6]
Hello Mathis,

I purchase a few Revision 1 PCB from Osh Park, and build a MMDV_Hs Pi Hat with RPi3.
Installed a 14.7456 MHz TCXO on it.

I tried to compile and install the ZUMspot RPi software on the MMDVM_HS Pi Hat with RPi3.
But I couldn't get it working properly.

I can see that ADF7021 CLKOUT has continuous clock signal output.
STM32 is working fine.

But it doesn't work with Pi-Star, either using STM32 MMDVM GPIO or ZUMspot GPIO.

I compiled firmware with latest code from MMDVM_HS on GitHub with following parameters:

#define PI_HAT_7021_REV_03
#define ENABLE_ADF7021
#define ADF7021_14_7456
#define STM32_USART1_HOST
#define ENABLE_SCAN_MODE

Is there anything else I should tweak or pay attention to?

Thanks for your help in advance!

Regards,
Yngwie

**Comment by yngwiechou** [comment]
I've managed to get it working, thanks!

**Comment by phl0** [comment]
What was the issue?

**Comment by yngwiechou** [comment]
I think I used the wrong firmware for that.
Need to use the Carrier board one. :)
