### ISSUE TITLE
BOM- linked Mouser  Carts

### ISSUE THREAD

**Issue by Jpbepler** [mathisschmieder/MMDVM_HS_Hat#7]
in the Mouser shopping cart your readme.md links to there are some incorrect parts:
C 14 -still wrong capacity in cart is 1µF should be 1nF  0402 -correct Nr: 81-GRM155R60J102KA1D 
C4 - is size "01005 in" instead of "0402 in" probably confused with "0402mm" value 10pF- correct Nr: 81-GRM1555C1E100JA1D
C8, C10, C15, C16, C20, C24-C28 is size "01005 in" instead of "0402 in" probably confused with "0402mm" value 100nF - correct Nr: 81-GRM022R60J104KE5L

same errors in the revision 1.2 and revision 1.1 carts

**Comment by phl0** [comment]
Jepp. Working on that. Hopefully correct by tonight.

**Comment by phl0** [comment]
Corrected both rev1.1 and rev1.2 Mouser carts.
