### ISSUE TITLE
Two Boards... same issue.

### ISSUE THREAD

**Issue by WC6Q** [mathisschmieder/MMDVM_HS_Hat#9]
HI!,
So I built two of the 1.2 boards. After flashing the firmware I tried both and everything works except for that there is no audio, and when I transmit to the boards nothing happens. I have doubled checked settings, such as frequency and the basic stuff. I have also verified that the components are oriented correctly. 
Any ideas what would cause such an issue? Or just a direction I should go? I am amazed both are acting the same way.

Thanks for your help and insight into my problem.

73,
Ryan
WC6Q

**Comment by phl0** [comment]
What do the LEDs say? Did you enable scan mode in the firmware? Are the mode LEDs blinking one after another when MMDVMHost is running?

**Comment by WC6Q** [comment]
LEDs were not circling, had power LED and a slow, then fast service LED. I checked the Config.h and sure enough none of the settings were right. (I switched to an older SD card and forgot to check that) Once I fixed Config.h everything came to life! Thank you for responding, and thanks for your help on this project. It's been fun! 73!! Ryan_WC6Q

**Comment by phl0** [comment]
Well congrats then. :+1:
